name: common
description: App common module
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
