name: game_browser
description: Game Browser App.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  domain_game:
    path: ../domain_game
  initializer:
    path: ../initializer
  intl: ^0.19.0
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.2
  auto_route: ^5.0.4
  injectable: ^2.1.0
  get_it: ^7.2.0

dev_dependencies:
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.3
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bdd_widget_test: ^1.4.3
  mocktail: ^0.3.0
  http_mock_adapter: ^0.4.2
  freezed: ^2.3.2
  bloc_test: ^9.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
